### ISSUE TITLE
Please provide update.json

### ISSUE THREAD

**Issue by IzzySoft** [reiryuki/ZRAM-Swap-Configurator-Magisk-Module#1]
Could you please provide an `update.json` for easy installation and updates? Thanks in advance!

**Comment by reiryuki** [comment]
pling.com doesn't support update.json

**Comment by IzzySoft** [comment]
I'm no module dev, so I might miss something here: what does `pling.com` have to do with providing an `update.json` here in your Github repo? To my knowledge, that file just holds:

```json
{
    "version": "<your_module_version>",
    "versionCode": <your_module_versionCode>,
    "zipUrl": "<url_to_your_compiled_module.zip>",
    "changelog": "<optional_url_to_your_changelog.md>"
}
```

This could be placed anywhere in your repo here, usually it's directly in the repo root. Your release process then would include updating that file. What did I miss? Apologies if I'm totally off the track – as said, I'm no module dev myself.

**Comment by reiryuki** [comment]
pling.com doesn't have direct download file

**Comment by IzzySoft** [comment]
Ah, I see – so that's what I missed. Would [tagging releases](https://github.com/reiryuki/ZRAM-Swap-Configurator-Magisk-Module/releases) and attaching the ZIP there be an option? Many other modules handle it that way. For some background to my question: I maintain [a module repo](https://apt.izzysoft.de/magisk) for Magisk Modules which are FOSS – and I'd like to include your module there. Currently, using `update.json` is the only way it can automatically keep things up-to-date, though other means might be implemented in the future.

**Comment by IzzySoft** [comment]
Oh, surprise! It seems the repo-util I'm using can create the module.zip directly from the git repo – I didn't expect that variant working that easy. Can you confirm the following ZIP of your module would be fine?

[v1.13_13.zip](https://github.com/reiryuki/ZRAM-Swap-Configurator-Magisk-Module/files/11133672/v1.13_13.zip)

That then would not only mean I could add it straight away – but it would save me a lot of head-aches for several others queued up here, waiting to be added :smiley:

**Comment by reiryuki** [comment]
I will never support 'talking only' without sending proper logs. If you want a fix, then read #bug_report carefully, and send required files to the author.

**Comment by reiryuki** [comment]
Use discussion tab instead next time

**Comment by IzzySoft** [comment]
Well, a clear "yes" or "no" from your end would have made a "discussion" unnecessary. But same as you said, I'm not about "talking only" – I just was asking for a straight answer I never got. I cannot use pling.com (doesn't work for me), you cannot tell me if just zipping up the cloned repo would produce a proper module (often it does, when developers keep the structure that way – but some modules need some different setup; as I cannot get a ready module to check against and you won't answer it I'll never know for yours) – so I have to give up on it then.  :cry:

So thanks for the invitation – but no need for a "next time" if I cannot get an answer anyway.

**Comment by reiryuki** [comment]
Support & Bug Report
https://t.me/androidryukimodsdiscussions/2618
If you don't do above, issues will be closed immediately
