### ISSUE TITLE
not working on Android 14?

### ISSUE THREAD

**Issue by Cathgao** [reiryuki/ZRAM-Swap-Configurator-Magisk-Module#3]
system: HyperOS1.0.1.0
Android: Android 14
Magisk: 27.0

I have creat /data/media/0/optionals.prop and save text below:
 ```
zram.resize=0
zram.algo=lz4
````

Then I install the module and reboot. But nothing changed. Is something wrong?
![Screenshot_2024-04-19-10-10-26-963_com liuzho fil](https://github.com/reiryuki/ZRAM-Swap-Configurator-Magisk-Module/assets/21031564/628c5691-a744-4689-9228-f2e95bc546f2)
![Screenshot_2024-04-19-10-09-53-416_jieclu hr man](https://github.com/reiryuki/ZRAM-Swap-Configurator-Magisk-Module/assets/21031564/3db2e848-121a-4487-908b-7e9fc3cdb099)
![Screenshot_2024-04-19-10-11-09-655_com byyoung se](https://github.com/reiryuki/ZRAM-Swap-Configurator-Magisk-Module/assets/21031564/931ca3ac-4666-4145-9358-fca6c7b86a46)
![Screenshot_2024-04-19-10-14-08-814_jieclu hr man](https://github.com/reiryuki/ZRAM-Swap-Configurator-Magisk-Module/assets/21031564/60c9291e-b890-41f7-8149-73d4af0a4156)

**Comment by Cathgao** [comment]
I reinstall it and here is the install log
[magisk_install_log_2024-04-19T10.24.05.log](https://github.com/reiryuki/ZRAM-Swap-Configurator-Magisk-Module/files/15032322/magisk_install_log_2024-04-19T10.24.05.log)

**Comment by reiryuki** [comment]
-------------- Any missing stuffs --------------
------------- will not be approved -------------

1) Explanations ✓
2) Magisk/KernelSU install log if it's a Magisk module #magisk_install_log ✓
3) Disable any other else modules (except the module you want to report, AML, dirac misoundfx Remover, AOSP soundfx Remover, & Sound Alive FX Remover Magisk Module. But if you are reporting for AML Ryuki Mod, then you need to enable all audio mod module you have.)
4) Z folder #zfolder

send magisk install log with optional debug.log=1 also
